import { useEffect, useRef, useState } from "react";

import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "../components/ui/alert-dialog";
import { buttonVariants } from "../components/ui/button";
import { canApproveVideoTts, formatTtsDuration, formatTtsRate, isActiveVideoTtsJob, requiresDurationDecision, videoTtsDeviationLabel, videoTtsJobLabel, type VideoTtsDurationDecision, type VideoTtsWorkspace } from "./video-tts-logic";
import { useVideoTts } from "./use-video-tts";

const inputClass = "mt-2 min-h-11 w-full rounded-md border border-[var(--border-strong)] bg-[var(--bg-canvas)] px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] disabled:cursor-not-allowed disabled:opacity-50";
const primaryButton = buttonVariants({ variant: "default" });
const secondaryButton = buttonVariants({ variant: "outline" });

function AudioReview({ base, workspace, busy, onRegenerate, onApprove }: { base: string; workspace: VideoTtsWorkspace; busy: boolean; onRegenerate: (notes: string) => void; onApprove: (notes: string, decision: "within_target" | "accept_actual") => void }) {
  const audioRef = useRef<HTMLAudioElement>(null);
  const artifact = workspace.artifact!;
  const [notes, setNotes] = useState(workspace.review?.notes ?? "");
  const [decision, setDecision] = useState<VideoTtsDurationDecision>(workspace.review?.durationDecision ?? null);
  const [confirmedFullPlayback, setConfirmedFullPlayback] = useState(false);
  const stale = artifact.stale || Boolean(workspace.snapshot?.stale);
  useEffect(() => { setNotes(workspace.review?.notes ?? ""); setDecision(workspace.review?.durationDecision ?? null); setConfirmedFullPlayback(false); }, [artifact.id, stale, workspace.review?.notes, workspace.review?.durationDecision]);
  const approved = Boolean(workspace.audioGate?.valid);
  const overBudget = requiresDurationDecision({ durationSeconds: artifact.durationSeconds, targetDurationSeconds: workspace.targetDurationSeconds });
  const approvalDecision = overBudget ? decision : "within_target";
  const candidate = { ...artifact, stale, targetDurationSeconds: workspace.targetDurationSeconds, durationDecision: approvalDecision, approved };
  const snapshot = workspace.snapshot;

  function seek(seconds: number) {
    if (!audioRef.current) return;
    audioRef.current.currentTime = seconds;
    void audioRef.current.play().catch(() => undefined);
  }

  return <section className="border-t border-[var(--border-subtle)] px-5 py-6 md:px-7" aria-labelledby="audio-review-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="audio-review-heading" className="text-base font-semibold">听音审核</h3><p className="mt-1 text-sm text-[var(--fg-secondary)]">完整试听后定位检查段落，并明确批准当前音频。</p></div><span className="rounded-md border border-[var(--border-strong)] px-2 py-1 text-xs font-semibold">{stale ? "历史 / 已失效" : approved ? "已批准" : "等待听音"}</span></div>
    {stale ? <p className="mt-4 border border-[var(--status-warning)] bg-[var(--status-warning-soft)] px-3 py-3 text-sm" role="alert">旁白或配音配置已变化。此音频仅供历史查看，不能再次批准。</p> : null}
    <audio ref={audioRef} className="mt-5 w-full" controls preload="metadata" src={`${base}/tts/audio`}>浏览器不支持音频播放。</audio>
    <label className="mt-2 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={confirmedFullPlayback} disabled={busy || stale || approved} onChange={(event) => setConfirmedFullPlayback(event.target.checked)} />我已完整试听当前音频</label>
    <dl className="mt-5 grid gap-3 bg-[var(--bg-subtle)] p-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-[var(--fg-tertiary)]">真实 / 目标时长</dt><dd className="mt-1 font-mono">{formatTtsDuration(artifact.durationSeconds)} / {formatTtsDuration(workspace.targetDurationSeconds)}</dd></div><div><dt className="text-[var(--fg-tertiary)]">绝对偏差</dt><dd className="mt-1 font-mono">{videoTtsDeviationLabel(artifact.durationSeconds, workspace.targetDurationSeconds)}</dd></div><div><dt className="text-[var(--fg-tertiary)]">供应商 / 模型</dt><dd className="mt-1 break-words">{snapshot ? `${snapshot.providerId} / ${snapshot.modelId}` : "--"}</dd></div><div><dt className="text-[var(--fg-tertiary)]">声音 / 语速 / 语言</dt><dd className="mt-1">{snapshot ? `${snapshot.voiceId} / ${formatTtsRate(snapshot.rate)} / ${snapshot.language}` : "--"}</dd></div></dl>
    {overBudget ? <fieldset className="mt-5 border-y border-[var(--border-subtle)] py-4" disabled={busy || stale || approved}><legend className="font-semibold text-[var(--status-warning)]">时长偏差超过 10%，批准前必须选择处理方式</legend><div className="mt-3 grid gap-2 text-sm"><label className="flex min-h-11 items-center gap-3"><input type="radio" name={`duration-${artifact.id}`} checked={decision === "accept_actual"} onChange={() => setDecision("accept_actual")} />接受实际时长并记录决定</label><label className="flex min-h-11 items-center gap-3"><input type="radio" name={`duration-${artifact.id}`} checked={decision === "reprocess"} onChange={() => setDecision("reprocess")} />调整语速并重新生成</label></div></fieldset> : null}
    <div className="mt-6 grid min-w-0 gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,.75fr)]"><section aria-labelledby="cue-heading"><h4 id="cue-heading" className="text-sm font-semibold">段落定位</h4><ol className="mt-3 max-h-80 divide-y divide-[var(--border-subtle)] overflow-y-auto border-y border-[var(--border-subtle)]">{workspace.cues.map((cue, index) => <li key={cue.id}><button className="grid min-h-11 w-full min-w-0 grid-cols-[4rem_minmax(0,1fr)] gap-3 px-3 py-3 text-left text-sm hover:bg-[var(--bg-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[var(--focus)]" type="button" onClick={() => seek(cue.startSeconds)}><span className="font-mono text-xs text-[var(--fg-tertiary)]">{formatTtsDuration(cue.startSeconds)}</span><span className="min-w-0"><strong>段落 {index + 1}</strong><span className="mt-1 block break-words leading-6 text-[var(--fg-secondary)]">{cue.text}</span></span></button></li>)}</ol></section>
      <section aria-labelledby="notes-heading"><h4 id="notes-heading" className="text-sm font-semibold">听音备注</h4><label className="sr-only" htmlFor={`audio-notes-${artifact.id}`}>专名读音、停连、语速与情绪备注</label><textarea id={`audio-notes-${artifact.id}`} className={`${inputClass} min-h-36 resize-y leading-6`} disabled={busy || stale || approved} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="记录专名读音、停连、语速或情绪问题。" /><div className="mt-3 flex flex-wrap gap-2"><button className={secondaryButton} type="button" disabled={busy || stale || approved} onClick={() => onRegenerate(notes)}>{busy ? "正在处理…" : "需要重新生成"}</button><button className={primaryButton} type="button" disabled={busy || !confirmedFullPlayback || !canApproveVideoTts(candidate)} onClick={() => onApprove(notes, approvalDecision as "within_target" | "accept_actual")}>{approved ? "当前音频已批准" : busy ? "正在批准…" : "批准当前音频"}</button></div></section></div>
    <div className="mt-5 flex flex-wrap gap-3 text-sm"><a className="min-h-11 py-3 font-semibold text-[var(--accent)] underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]" href={`${base}/tts/subtitles/srt`} download>下载 SRT</a><a className="min-h-11 py-3 font-semibold text-[var(--accent)] underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]" href={`${base}/tts/subtitles/ass`} download>下载 ASS</a></div>
  </section>;
}

export function VideoAudioStage({ projectId, videoId, onReturnToScript }: { projectId: string; videoId: string; onReturnToScript?: () => void }) {
  const state = useVideoTts(projectId, videoId);
  const workspace = state.workspace;
  const [voiceId, setVoiceId] = useState(""); const [rate, setRate] = useState(0); const [language, setLanguage] = useState("");
  const configRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!workspace?.provider) return; setVoiceId(workspace.provider.voiceId); setRate(workspace.provider.rate); setLanguage(workspace.provider.language); }, [workspace?.provider?.voiceId, workspace?.provider?.rate, workspace?.provider?.language]);
  if (!state.loaded) return <section className="p-6 text-sm text-[var(--fg-secondary)]" aria-live="polite">正在恢复配音与字幕状态…</section>;
  if (!workspace) return <section className="p-6" role="alert"><h2 className="text-lg font-semibold">无法恢复配音工作区</h2><p className="mt-2 text-sm">{state.status}</p><button className={`${secondaryButton} mt-5`} type="button" onClick={() => void state.refresh()}>重新加载</button></section>;
  const base = `/api/projects/${encodeURIComponent(projectId)}/videos/${encodeURIComponent(videoId)}`;
  const active = isActiveVideoTtsJob(workspace.job); const busy = state.busyAction !== null;
  const providerLabel = workspace.provider ? `${workspace.provider.name || workspace.provider.id} / ${workspace.provider.modelId}` : "未配置";
  const statusLabel = workspace.audioGate?.valid ? "已批准" : videoTtsJobLabel(workspace.job);

  return <section className="min-w-0" aria-labelledby="audio-stage-heading"><header className="border-b border-[var(--border-subtle)] bg-[var(--bg-subtle)] px-5 py-5 md:px-7"><p className="font-mono text-[11px] font-semibold tracking-[.14em] text-[var(--accent)]">MVP 第四阶段</p><h2 id="audio-stage-heading" className="mt-2 text-xl font-semibold">配音与字幕</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--fg-secondary)]">当前旁白方案有效即可独立生成，不等待图片审核。本阶段不会生成视觉时间轴、渲染或导出视频。</p><div className={`mt-4 min-h-11 border px-3 py-3 text-sm ${state.actionState === "error" ? "border-[var(--danger)] bg-[var(--danger-soft)] text-[var(--danger)]" : "border-[var(--border-subtle)] bg-[var(--bg-surface)]"}`} aria-live="polite" role={state.actionState === "error" ? "alert" : "status"}>{state.status}{workspace.blockedReason ? <p className="mt-1 font-semibold text-[var(--status-warning)]">当前阻断：{workspace.blockedReason}</p> : null}</div></header>
    <div ref={configRef} className="px-5 py-6 md:px-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-base font-semibold">生成配置</h3><p className="mt-1 text-sm text-[var(--fg-secondary)]">MVP 使用当前供应商真实支持的声音、语速与语言。</p></div><span className="rounded-md border border-[var(--border-strong)] px-2 py-1 text-xs font-semibold" role="status" aria-live="polite">{statusLabel}</span></div>{workspace.job?.status === "failed" && workspace.job.errorSummary ? <p className="mt-3 text-sm text-[var(--danger)]" role="alert">生成失败：{workspace.job.errorSummary}。请修正配置后重新生成。</p> : null}<div className="mt-5 grid min-w-0 gap-4 sm:grid-cols-3"><label className="min-w-0 text-sm font-semibold">声音<input className={inputClass} disabled value={voiceId} onChange={(event) => setVoiceId(event.target.value)} /></label><label className="min-w-0 text-sm font-semibold">语速档位（-10 至 +10）<input className={inputClass} disabled={active || busy} type="number" min="-10" max="10" step="1" value={rate} onChange={(event) => setRate(Number(event.target.value))} /></label><label className="min-w-0 text-sm font-semibold">语言<input className={inputClass} disabled value={language} onChange={(event) => setLanguage(event.target.value)} /></label></div>
      <dl className="mt-5 grid gap-3 bg-[var(--bg-subtle)] p-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-[var(--fg-tertiary)]">供应商 / 模型</dt><dd className="mt-1 break-words">{providerLabel}</dd></div><div><dt className="text-[var(--fg-tertiary)]">目标时长</dt><dd className="mt-1 font-mono">{formatTtsDuration(workspace.targetDurationSeconds)}</dd></div><div><dt className="text-[var(--fg-tertiary)]">预计步骤</dt><dd className="mt-1">生成音频 → 校验 → 字幕</dd></div><div><dt className="text-[var(--fg-tertiary)]">预计费用</dt><dd className="mt-1">费用未知</dd></div></dl>
      <div className="mt-5 flex flex-wrap gap-2">{active && workspace.job ? <button className={secondaryButton} type="button" disabled={busy} onClick={() => void state.cancel()}>{state.busyAction === "cancel" ? "正在中断…" : "中断任务"}</button> : <AlertDialog><AlertDialogTrigger className={primaryButton} disabled={!workspace.available || !workspace.provider || busy || !Number.isInteger(rate) || rate < -10 || rate > 10}>生成配音与字幕</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>确认生成配音与字幕</AlertDialogTitle><AlertDialogDescription asChild><div className="space-y-3"><p>此操作会创建持久任务并可能计费。只生成真实音频和字幕，不渲染视频。</p><dl className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-4 gap-y-2 text-[var(--fg-primary)]"><dt>供应商 / 模型</dt><dd className="break-words">{providerLabel}</dd><dt>声音 / 语速 / 语言</dt><dd>{voiceId} / {formatTtsRate(rate)} / {language}</dd><dt>目标时长</dt><dd>{formatTtsDuration(workspace.targetDurationSeconds)}</dd><dt>预计费用</dt><dd>费用未知</dd></dl></div></AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>返回检查</AlertDialogCancel><AlertDialogAction className={primaryButton} onClick={() => void state.start(voiceId, rate, language)}>确认生成</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div>
    </div>
    {workspace.artifact ? <AudioReview base={base} workspace={workspace} busy={busy} onRegenerate={(notes) => { if (workspace.snapshot && workspace.artifact) void state.requestRegeneration(workspace.snapshot.id, workspace.artifact.id, notes); configRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }} onApprove={(notes, decision) => { if (workspace.snapshot && workspace.artifact) void state.approve(workspace.snapshot.id, workspace.artifact.id, notes, decision); }} /> : null}
    {workspace.history.length ? <section className="border-t border-[var(--border-subtle)] px-5 py-6 md:px-7" aria-labelledby="audio-history-heading"><h3 id="audio-history-heading" className="text-base font-semibold">历史配音</h3><p className="mt-1 text-sm text-[var(--fg-secondary)]">旧身份仅供试听，不参与当前 audio gate。</p><ul className="mt-4 grid gap-4">{workspace.history.map((item) => <li key={item.id} className="min-w-0 border-y border-[var(--border-subtle)] py-4"><p className="break-words text-sm font-semibold">{item.providerId} / {item.modelId} / {item.voiceId} / {formatTtsRate(item.rate)} / {item.language}</p><p className="mt-1 text-xs text-[var(--fg-tertiary)]">已失效 · 真实时长 {formatTtsDuration(item.durationSeconds)}</p><audio className="mt-3 w-full" controls preload="metadata" src={`${base}/tts/artifacts/${encodeURIComponent(item.id)}/audio`}>浏览器不支持音频播放。</audio></li>)}</ul></section> : null}
    {onReturnToScript ? <div className="border-t border-[var(--border-subtle)] px-5 py-4 md:px-7"><button className={secondaryButton} type="button" onClick={onReturnToScript}>返回修改旁白</button></div> : null}
  </section>;
}
