import type { AssetRecord, EpisodeRecord, PromptParts } from "./types";
import { ASSET_TYPE_LABEL } from "./types";

const control = "min-h-10 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--bg-subtle)] px-2.5 text-sm text-[var(--fg-primary)]";

export function ImagePromptBuilder({ asset, episode, busy, alias, prompt, derivedFromCandidateId, parts, draftKind, onDraftKind, onDraft, onAlias, onAddAlias, onPart, onPrompt, onGenerate }: { asset?: AssetRecord; episode?: EpisodeRecord; busy: boolean; alias: string; prompt: string; derivedFromCandidateId?: string; parts: PromptParts; draftKind: "character" | "scene" | "prop" | "story"; onDraftKind: (value: "character" | "scene" | "prop" | "story") => void; onDraft: () => void; onAlias: (value: string) => void; onAddAlias: () => void; onPart: (key: keyof PromptParts, value: string) => void; onPrompt: (value: string) => void; onGenerate: () => void }) {
  if (!asset) return <section className="min-w-0 border-r border-[var(--border-subtle)] p-10 max-md:border-r-0 max-md:border-b"><p className="text-[13px] text-[var(--fg-tertiary)]">资产身份、状态和别名先于生图提示词。创建或选择资产后继续。</p></section>;
  const fields = [["evidence", "原文与批准稿事实", "只写可回到原文或已批准成片旁白稿的事实", true], ["sceneIntent", "场景意图", "例如：建立未知危险、交代人物关系", false], ["subjectAction", "主体与动作", "人物/道具正在做什么", false], ["environment", "环境", "地点、年代、空间与氛围", false], ["lightingComposition", "光线与构图", "光线、景别、视角、主体位置", false], ["styleConstraints", "风格与约束", "", true]] as const;
  return <section className="min-w-0 border-r border-[var(--border-subtle)] p-[clamp(24px,3vw,48px)] max-md:border-r-0 max-md:border-b" aria-labelledby="asset-inspector-heading">
    <p className="mb-2 font-mono text-[11px] font-semibold tracking-[.17em] text-[var(--accent)]">ASSET / PROMPT ASSEMBLY</p><h2 id="asset-inspector-heading" className="m-0 font-serif text-[clamp(28px,3vw,46px)] font-semibold leading-tight">{asset.name}</h2>
    <div className="my-4 flex flex-wrap gap-2">{[ASSET_TYPE_LABEL[asset.type], asset.role === "master" ? "主资产" : `状态：${asset.stateLabel}`, `${asset.aliases.length} 个别名`].map((item) => <span key={item} className="rounded-full border border-[var(--border-subtle)] px-2 py-1 text-[10px] text-[var(--fg-secondary)]">{item}</span>)}</div>
    <div className="mb-4 grid grid-cols-[1fr_auto] gap-2"><input className={control} value={alias} disabled={busy} onChange={(event) => onAlias(event.target.value)} placeholder="新增别名" aria-label="新增资产别名" /><button className="rounded border border-[var(--border-strong)] px-3 text-xs hover:bg-[var(--bg-subtle)] disabled:opacity-50" type="button" disabled={busy || !alias.trim()} onClick={onAddAlias}>保存别名</button></div>
    <div className="mb-4 grid grid-cols-[minmax(0,1fr)_auto] gap-2 border-y border-[var(--border-subtle)] py-3">
      <label className="grid gap-1.5 text-[11px] font-semibold text-[var(--fg-secondary)]">草稿用途<select className={control} value={draftKind} disabled={busy} onChange={(event) => onDraftKind(event.target.value as typeof draftKind)}><option value="character">人物定妆</option><option value="scene">场景设定</option><option value="prop">道具设定</option><option value="story">剧情插图</option></select></label>
      <button type="button" className="min-h-11 self-end rounded border border-[var(--border-strong)] px-4 text-sm font-semibold hover:bg-[var(--bg-subtle)] disabled:opacity-50" disabled={busy || !episode} onClick={onDraft}>{busy ? "正在处理…" : "生成可编辑草稿"}</button>
      <p className="col-span-2 m-0 text-xs leading-5 text-[var(--fg-tertiary)]">只生成文字草稿，不会生图、批准候选或绑定视觉段。修改确认后再手动创建生图任务。</p>
    </div>
    <div className="grid gap-2">{fields.map(([key, label, placeholder, multiline]) => <label key={key} className="grid gap-1.5 text-[11px] font-semibold text-[var(--fg-secondary)]">{label}{multiline ? <textarea className={`${control} min-h-20 resize-y py-2.5`} value={parts[key]} onChange={(event) => onPart(key, event.target.value)} placeholder={placeholder} /> : <input className={control} value={parts[key]} onChange={(event) => onPart(key, event.target.value)} placeholder={placeholder} />}</label>)}</div>
    <label className="my-4 grid gap-2 border-l-[3px] border-[var(--accent)] bg-[var(--bg-subtle)] p-3.5"><span className="font-mono text-[10px] text-[var(--fg-tertiary)]">{derivedFromCandidateId ? `从候选 ${derivedFromCandidateId.slice(0, 12)}… 恢复的完整 prompt` : "最终组装 prompt"}</span><textarea className={`${control} min-h-32 resize-y py-2.5 text-xs leading-6`} value={prompt} disabled={busy} onChange={(event) => onPrompt(event.target.value)} /></label>
    <button type="button" className="min-h-11 rounded bg-[var(--accent)] px-4 text-sm font-semibold text-[var(--accent-contrast)] hover:bg-[var(--accent-strong)] disabled:opacity-50" disabled={busy || !episode || !prompt.trim() || (!derivedFromCandidateId && (!parts.evidence.trim() || !parts.sceneIntent.trim() || !parts.subjectAction.trim()))} onClick={onGenerate}>{episode ? `确认当前 Prompt 并为第 ${episode.index} 集生成候选图` : "先完成分集和成片旁白稿批准"}</button>
  </section>;
}
